### ISSUE TITLE
Feature request:  Do not exit party menu after using item

### ISSUE THREAD

**Issue by fabianPas** [danenders/pkedx#28]
As the title says, it would be a nice quality of life feature to be able to use an type of item multiple times without leaving the party menu after using an item on a Pokémon. For example, having 5 potions in the inventory and using one, I would like to still be able to give 4 more to the same of different Pokémon without leaving the party menu.

**Comment by danenders** [comment]
Thank you for the feedback. More features are not being added to this project at this time, but please let me know if you run into any issues or bugs.

I'll consider this for my next project!
