### ISSUE TITLE
Feature request: Pressing left or right trigger in battle on selected move displays move information

### ISSUE THREAD

**Issue by fabianPas** [danenders/pkedx#29]
I would like to request a quality of life feature where pressing the left or right trigger in battle on a selected move shows information about that move. For example accuracy and power.

**Comment by danenders** [comment]
Thank you for the feedback. More features are not being added to this project at this time, but please let me know if you run into any issues or bugs.

I'll consider this for my next project!

**Comment by fabianPas** [comment]
Ohhhh, I was under the impression you were still actively developing for DX. Maybe I would make a PR then, would that be something you might merge?
